language: php
php:
    - '7.2'
    - '7.3'
install:
    - pecl install ds
    - composer install
script:
    - composer test
after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
